spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss15_ex1_entity?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

server:
  port: 8301

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8300/oauth/check_token
    client:
      client-id: client
      client-secret: secret